version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    parallelism: 15
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
